### ISSUE TITLE
code for paper?

### ISSUE THREAD

**Issue by waichee** [jamie-murdoch/ContextualDecomposition#1]
Hi

Thanks for the interesting paper on ICLR 2018
I have been linked from the paper to this repo, any chance that you have the code available here?
https://openreview.net/pdf?id=rkRwGg-0Z

**Comment by jamie-murdoch** [comment]
Hi! Sorry for the confusion, the code should be up by March 31

**Comment by mgrenander** [comment]
Hi,

I also wanted to say thanks for this great paper. I am very interested in reproducing the results whenever the code is available.

**Comment by jamie-murdoch** [comment]
I've posted code to compute CD scores from a trained SST classifier
