### ISSUE TITLE
"Absolute score" of a logistic regression classifier

### ISSUE THREAD

**Issue by taodav** [jamie-murdoch/ContextualDecomposition#3]
In the paper in 4.3, you mention a phrase is included if their absolute score is above 1.5. In this context, what does absolute score reference?

**Comment by jamie-murdoch** [comment]
I believe the (full) sentence you're referencing is

"Phrases are scored using the logistic regression with n-gram features described in Section 4.1, and included if their absolute score is over 1.5."

So, absolute score denotes the score computed from the ngram logistic regression (very basic, follows Zhang et. al 2016, and described in 4.1.2). In particular, for a given phrase, the corresponding score is the sum of the scores for the words and ngrams contained within that phrase
