### ISSUE TITLE
multiclass LSTM and unigram scores

### ISSUE THREAD

**Issue by goodluck321** [jamie-murdoch/ContextualDecomposition#4]
Hi

Thanks for sharing your code! Nice work.

From my understanding of the paper (section 3.2) CD can be applied to a multiclass LSTM classifier to decompose its predictions.

So, e.g., in order to quantify the contribution of a word to the LSTM's prediction for class j, one has to run the function `CD(batch, model, start, stop)` from the file `sent_util.py` with `start` and `stop` arguments equal to the index of the word of interest, and the resulting word score will be the value at the j-th position in the first returned numpy array `scores`. 
Hence, to get an importance score for every word within an input sequence, one has to repeat the above computation several times, and adapt the `start `and `stop` indices accordingly.

Is that the correct way of obtaining unigram scores? (I would like to reproduce the results of the paper section 4.2 + Table 1)
Or could you add a demo for computing these unigram scores?

Thanks in advance for clarifying this point.

**Comment by jamie-murdoch** [comment]
Thanks for your interest!

You are correct. Given a phrase, the CD algorithm/implementation produces a vector of scores, one for each class. In this sense, a word is a phrase of length one, so to get unigram scores for the full sentence you can call CD separately for each word in the document.

**Comment by mgrenander** [comment]
Hi,

I noticed in the ``demo.ipynb`` file you computed the score of the phrase ``it 's easy to love robin tunney -- she 's pretty and she can act`` by computing ``pos[0] - pos[1]``.

Could you explain why you are subtracting the scores here instead of simply using the j-th position for the score of the j-th class?

Also - are the figures in the report similarly computed by taking the difference of the scores?

Thank you very much!

**Comment by jamie-murdoch** [comment]
Yes, the figures in the report are computed using the difference in scores. There's a number of different justifications for this, but the short answer is it doesn't really make a difference. 

Mathematically, an LSTM learns an overparameterized logistic regression (normally, for binary classification, the coefficients would be one dimensional). Converting to a standard logistic regression corresponds to dividing the numerator and denominator in the softmax by exp(beta_{negative}), which is the same as taking the difference in scores. Empirically, I generally observe that the positive score is essentially equal to the negative of the positive score (although this is not guaranteed mathematically), which would mean that I'd expect the distributions for individual scores to look essentially the same. 

This should be noted in the paper though, so I'll add a line in the new arXiv version.

**Comment by mgrenander** [comment]
Thank you for clarifying this point!
