### ISSUE TITLE
Bias decomposition differs from paper

### ISSUE THREAD

**Issue by jumelet** [jamie-murdoch/ContextualDecomposition#5]
Hi! Thanks a lot for sharing the code, I've been investigating Contextual Decomposition thoroughly the past few weeks.

I was wondering why you add the bias interaction of the input gate to the relevant part here:
https://github.com/jamie-murdoch/ContextualDecomposition/blob/e6575aac713ea1d7f96f662a08659ffaa000c7d5/train_model/sent_util.py#L142-L145

This is different from the paper, equation (32) always adds this interaction to gamma. That seems reasonable to me as well, this interaction does not depend on the input at all.

**Comment by jamie-murdoch** [comment]
Thanks for your interest, and good catch! In short, this was an adjustment to CD that we made after the paper was published, when working on agglomerative CD (ACD) (https://arxiv.org/abs/1806.05337, https://github.com/csinva/acd). 

Some context: the original CD code from the paper (that was used to generate the results) was actually in the now-dormant torch library. This is a re-implementation of CD in pytorch that we used in our follow-on ACD project, which I'd recommend looking at (it's a better method, and the code is better).

This rationale behind this change was that it made the CD score of the entire sentence be equal to the prediction, which was particularly important/desirable when doing ACD. Without the change, regardless of what phrase you choose, those bias terms would always be separate.

Hope this helps!
Jamie
